/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Octaviano
 */
public class ViewBlocNotas extends javax.swing.JFrame {

    /**
     * Creates new form ViewBlocNotas
     */
    public ViewBlocNotas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jta_contenido = new javax.swing.JTextArea();
        jfc_archivos = new javax.swing.JFileChooser();
        jl_titulo = new javax.swing.JLabel();
        jl_cifrado = new javax.swing.JLabel();
        jtf_cifrado = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_archivo = new javax.swing.JMenu();
        jmi_leer = new javax.swing.JMenuItem();
        jmi_guardar = new javax.swing.JMenuItem();
        jmi_cifrar = new javax.swing.JMenuItem();
        jmi_descifrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta_contenido.setColumns(20);
        jta_contenido.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        jta_contenido.setRows(5);
        jScrollPane1.setViewportView(jta_contenido);

        jl_titulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jl_titulo.setForeground(new java.awt.Color(255, 102, 102));
        jl_titulo.setText("Bloc de Notas con Cifrado Cesar..!!");

        jl_cifrado.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jl_cifrado.setText("Ingrese su propio cifrado cesar");

        jMenuBar1.setBackground(new java.awt.Color(255, 51, 51));

        jm_archivo.setBackground(new java.awt.Color(255, 153, 153));
        jm_archivo.setText("Archivo");

        jmi_leer.setBackground(new java.awt.Color(255, 204, 204));
        jmi_leer.setText("Leer");
        jm_archivo.add(jmi_leer);

        jmi_guardar.setBackground(new java.awt.Color(255, 204, 204));
        jmi_guardar.setText("Guardar");
        jm_archivo.add(jmi_guardar);

        jmi_cifrar.setBackground(new java.awt.Color(255, 204, 204));
        jmi_cifrar.setText("cifrar");
        jm_archivo.add(jmi_cifrar);

        jmi_descifrar.setBackground(new java.awt.Color(255, 204, 204));
        jmi_descifrar.setText("descifrar");
        jm_archivo.add(jmi_descifrar);

        jMenuBar1.add(jm_archivo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jl_titulo)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jl_cifrado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtf_cifrado)))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_cifrado)
                    .addComponent(jtf_cifrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewBlocNotas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewBlocNotas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JFileChooser jfc_archivos;
    public javax.swing.JLabel jl_cifrado;
    public javax.swing.JLabel jl_titulo;
    public javax.swing.JMenu jm_archivo;
    public javax.swing.JMenuItem jmi_cifrar;
    public javax.swing.JMenuItem jmi_descifrar;
    public javax.swing.JMenuItem jmi_guardar;
    public javax.swing.JMenuItem jmi_leer;
    public javax.swing.JTextArea jta_contenido;
    public javax.swing.JTextField jtf_cifrado;
    // End of variables declaration//GEN-END:variables
}
